#!/usr/bin/env python3
import sys
import random
import pprint


class Board:
    positions = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    used = {}
    winners = [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [1,4,7],
        [2,5,8],
        [3,6,9],
        [1,5,9],
        [3,5,7],
    ]

    def move(self, player, pos):
        self.used[int(pos)] = int(player)

    def available(self):
        free = []
        for pos in self.positions:
            if pos not in self.used.keys():
                free.append(pos)

        return free

    def winner(self):
        for player in [1,2]:
            owned = []
            for pos in self.used.keys():
                if self.used[pos] == player:
                    owned.append(pos)

            for combination in self.winners:
                matched = 0
                for pos in combination:
                    if pos in owned:
                        matched += 1

                if matched == 3:
                    return player

        return None

    def won(self):
        return self.winner() is not None


class AIPlayer:

    def prompt(self, board: Board):
        return random.choice(board.available())


class CliPlayer:

    def prompt(self, board: Board):
        pos = "0"
        options = board.available()
        while int(pos) not in options:
            pos = input("Choose your move (" + ",".join(map(str, options)) + ")")

        return pos


class UI:

    players = {}

    def __init__(self, board: Board, player1, player2):
        self.playerShapes = {
            1: 'X',
            2: 'O'
        }
        self.board = board
        self.players[1] = player1
        self.players[2] = player2

    def run(self):
        print("Welcome to naughts and crosses. Player 1 is crosses")
        player = 2

        while self.board.available():

            # Toggle to the next player
            if player == 1:
                print("Player 2 turn")
                player = 2
            elif player == 2:
                print("Player 1 turn")
                player = 1

            pos = self.players[player].prompt(self.board)
            self.board.move(player, pos)
            self.draw()

            # Check for victory condition
            if self.board.won():
                winner = self.board.winner()
                print("The game has been won by " + self.symbol(winner))
                exit()

        print("The game was a draw")

    def symbol(self, player):
        return self.playerShapes.get(player)

    def draw(self):

        for pos in self.board.positions:
            if pos in self.board.used.keys():
                player = self.board.used[pos]
                symbol = self.symbol(player)
            else:
                symbol = " "

            sys.stdout.write(symbol + ("\n" if (pos+1) % 3 == 1 else "|"))

        sys.stdout.write("\n")


# Run it
ui = UI(Board(), CliPlayer(), AIPlayer())
# ui = UI(Board(), AIPlayer(), AIPlayer())
ui.run()
